# Generated by Django 3.2 on 2021-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210502_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, default='https://icon-library.com/images/no-image-icon/no-image-icon-0.jpg'),
        ),
    ]
