# Generated by Django 3.2 on 2021-05-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_listings_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='current_bid',
        ),
    ]
