# Generated by Django 3.2 on 2021-05-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_start_bid_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='title',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
